# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingEventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField()),
                ('chefdejour', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('remarks', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('rezeptbild', wagtail.wagtailcore.fields.StreamField((('Bild', wagtail.wagtailcore.blocks.StructBlock((('rezept_bild', wagtail.wagtailimages.blocks.ImageChooserBlock()),))),))),
                ('mengepersonen', models.CharField(max_length=100)),
                ('kommentar', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('gang', models.CharField(choices=[('AP', 'Apéro'), ('VO', 'Vorspeise'), ('HG', 'Hauptgang'), ('DE', 'Dessert')], default='HG', max_length=2)),
                ('body', wagtail.wagtailcore.fields.StreamField((('RecipeTopBottomBlock', wagtail.wagtailcore.blocks.StructBlock((('untertitel', wagtail.wagtailcore.blocks.StreamBlock((('Untertitel', wagtail.wagtailcore.blocks.RichTextBlock(required=False)),))), ('zutaten', wagtail.wagtailcore.blocks.StreamBlock((('Zutat', wagtail.wagtailcore.blocks.StructBlock((('amount', wagtail.wagtailcore.blocks.CharBlock(classname='full', label='Menge')), ('ingredient', wagtail.wagtailcore.blocks.CharBlock(classname='full', label='Zutat'))), required=False)),))), ('arbeitsschritte', wagtail.wagtailcore.blocks.StreamBlock((('Arbeitsschritt', wagtail.wagtailcore.blocks.RichTextBlock(required=False)),)))))), ('RecipeLeftRightBlock', wagtail.wagtailcore.blocks.StructBlock((('untertitel', wagtail.wagtailcore.blocks.StreamBlock((('Untertitel', wagtail.wagtailcore.blocks.RichTextBlock(required=False)),))), ('zutatenarbeitsschritte', wagtail.wagtailcore.blocks.StreamBlock((('ZutatArbeitsschritt', wagtail.wagtailcore.blocks.StructBlock((('amount', wagtail.wagtailcore.blocks.CharBlock(classname='full', label='Menge')), ('ingredient', wagtail.wagtailcore.blocks.CharBlock(classname='full', label='Zutat')), ('instruktion', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', label='Arbeitsschritt'))), required=False)),)))))), ('RecipeFreeFormBlock', wagtail.wagtailcore.blocks.StructBlock((('untertitel', wagtail.wagtailcore.blocks.StreamBlock((('Untertitel', wagtail.wagtailcore.blocks.RichTextBlock(required=False)),))), ('instruktionen', wagtail.wagtailcore.blocks.StreamBlock((('Instruktion', wagtail.wagtailcore.blocks.RichTextBlock(required=False)),))))))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
