# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('cooking', '0003_remove_cookingeventpage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingeventpage',
            name='recipefile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
